name: flutter_sensitive_content
description: A Flutter package for hiding the sensitive content of your app when you switch from one app to another. This way, no sensitive pieces of information are shown while the app previews.
version: 0.0.3
homepage: https://github.com/CarloDotLog/flutter_sensitive_content
repository: https://github.com/CarloDotLog/flutter_sensitive_content

# This package supports only platforms listed below.
platforms:
  android:
  ios:
  web:
  macos:

environment:
  sdk: '>=3.1.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter: