name: flutter_sensitive_content
description: A Flutter package to hide the sensitive content of your app when you switch to another app. So no sensitive
  information are showed when the app previewer is showed.
version: 0.0.1
homepage: https://github.com/CarloDotLog/flutter_sensitive_content
repository: https://github.com/CarloDotLog/flutter_sensitive_content

# This package supports only platforms listed below.
platforms:
  android:
  ios:

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter: